package app

import (
	"strings"
	"time"

	tea "charm.land/bubbletea/v2"
	"charm.land/lipgloss/v2"
	"github.com/tuna-os/bluefin-cli/internal/tui/theme"
)

// dino is the dot-matrix raptor that runs along the header's braille
// seafloor. The sprite is a two-row braille rendering of an 8x14 pixel
// grid modeled on the Chrome offline T-rex (boxy head with an eye notch,
// tail rising to the left, alternating legs); frames are generated by
// tmp/braillegen.py. It ambles, pauses to look around, and sprints for a
// moment whenever the user selects something.
const dinoTop = "⣀⠀⠀⢀⣀⣯⠿"

var dinoRunFrames = []string{
	"⠙⢷⠾⠿⢿⠉", // legs apart
	"⠙⠷⣾⠿⣿⠉", // legs tucked
}

// dinoPauseFrame is shown when the dino stops to look around.
const dinoPauseFrame = "⠙⢷⡾⠿⣿⠉"

const (
	dinoFPS        = 8  // ticks per second
	dinoStrideCols = 1  // columns advanced per tick while ambling
	dinoSprintCols = 3  // columns advanced per tick while sprinting
	dinoPauseEvery = 36 // ticks between pauses
	dinoPauseLen   = 10 // ticks a pause lasts
	dinoSprintLen  = 10 // ticks a selection sprint lasts
)

// groundPattern repeats to form the seafloor; mild variation reads as
// terrain rather than a flat rule.
var groundPattern = []rune("⣀⣀⣀⣀⣄⣀⣀⣀⡀⣀⣀⣠⣀⣀⣀⣀")

type dino struct {
	x      int // leading (left) column of the sprite
	ticks  int
	sprint int // remaining sprint ticks
}

func (d *dino) tick() tea.Cmd {
	return tea.Tick(time.Second/dinoFPS, func(time.Time) tea.Msg { return dinoTickMsg{} })
}

// boost makes the dino sprint briefly — fired when the user selects
// something, so navigation has a little kinetic feedback.
func (d *dino) boost() {
	d.sprint = dinoSprintLen
}

func (d *dino) paused() bool {
	return d.sprint == 0 && d.ticks%(dinoPauseEvery+dinoPauseLen) >= dinoPauseEvery
}

func (d *dino) advance(width int) {
	d.ticks++
	if d.paused() {
		return
	}
	stride := dinoStrideCols
	if d.sprint > 0 {
		d.sprint--
		stride = dinoSprintCols
	}
	d.x += stride
	spriteW := len([]rune(dinoTop))
	if width > 0 && d.x > width {
		// Ran off the right edge; re-enter from the left.
		d.x = -spriteW
	}
}

// clip trims a sprite row to the visible [0, width) range for a sprite whose
// left edge is at column start. It returns the visible runes and the column
// they begin at; ok is false when nothing is visible.
func clip(row []rune, start, width int) (vis []rune, at int, ok bool) {
	if start+len(row) <= 0 || start >= width {
		return nil, 0, false
	}
	if start < 0 {
		row = row[-start:]
		start = 0
	}
	if start+len(row) > width {
		row = row[:width-start]
	}
	return row, start, true
}

// renderGround draws the dino's two rows: a sky line holding the head and
// tail, and a full-width braille seafloor with the legs spliced in. A blank
// cell each side of the leg row clears the ground so the (also braille)
// sprite stands out; sprinting kicks up a dust trail behind.
func (d *dino) renderGround(width int, t theme.Theme) string {
	if width < 1 {
		return ""
	}
	ground := make([]rune, width)
	for i := range ground {
		ground[i] = groundPattern[i%len(groundPattern)]
	}
	groundStyle := lipgloss.NewStyle().Foreground(t.Surface)
	dinoStyle := lipgloss.NewStyle().Foreground(t.Success).Bold(true)

	bottom := dinoRunFrames[d.ticks%len(dinoRunFrames)]
	if d.paused() {
		bottom = dinoPauseFrame
	}
	pad := " "
	if d.sprint > 0 {
		pad = " ⋅∘ "
	}
	top := []rune(strings.Repeat(" ", len([]rune(pad))) + dinoTop + " ")
	bot := []rune(pad + bottom + " ")

	sky := strings.Repeat(" ", width)
	if vis, at, ok := clip(top, d.x, width); ok {
		sky = strings.Repeat(" ", at) + dinoStyle.Render(string(vis)) +
			strings.Repeat(" ", width-at-len(vis))
	}

	floor := groundStyle.Render(string(ground))
	if vis, at, ok := clip(bot, d.x, width); ok {
		floor = groundStyle.Render(string(ground[:at])) +
			dinoStyle.Render(string(vis)) +
			groundStyle.Render(string(ground[at+len(vis):]))
	}
	return sky + "\n" + floor
}
