package app

import (
	"strings"
	"time"

	tea "charm.land/bubbletea/v2"
	"charm.land/lipgloss/v2"
	"github.com/tuna-os/bluefin-cli/internal/tui/theme"
)

// dino is the dot-matrix raptor that runs along the header's braille
// seafloor. The sprite is a three-row braille rendering of a 14x12 pixel
// grid hand-reduced from the real Chrome offline T-rex sprite (frames
// generated by scripts/braillegen.py): head with eye notch top-right, tail
// sweeping down-left, alternating legs. It ambles, pauses to look around,
// and sprints for a moment whenever the user selects something.
//
// Every character in the sprite rows is braille (blanks are U+2800, not
// ASCII spaces): some fonts draw braille double-wide, and mixing widths
// across rows would shear the sprite apart.
const (
	dinoSkyHigh = "⠀⠀⠀⠀⣯⣿⠿" // head + eye
	dinoSkyLow  = "⢷⣄⣠⣾⣿⣿⡠" // tail into body + arm
)

var dinoLegFrames = []string{
	"⠀⠙⡿⠻⢿⠋⠀", // stride A
	"⠀⠙⢿⠻⡿⠋⠀", // stride B
}

// dinoLegsPause is shown when the dino stops to look around.
const dinoLegsPause = "⠀⠙⡿⠻⡿⠋⠀"

// dinoDust trails behind the legs while sprinting.
const dinoDust = "⠐⠂"

const (
	dinoFPS        = 8  // ticks per second
	dinoStrideCols = 1  // columns advanced per tick while ambling
	dinoSprintCols = 3  // columns advanced per tick while sprinting
	dinoPauseEvery = 36 // ticks between pauses
	dinoPauseLen   = 10 // ticks a pause lasts
	dinoSprintLen  = 10 // ticks a selection sprint lasts
)

// groundPattern repeats to form the seafloor; mild variation reads as
// terrain rather than a flat rule.
var groundPattern = []rune("⣀⣀⣀⣀⣄⣀⣀⣀⡀⣀⣀⣠⣀⣀⣀⣀")

type dino struct {
	x      int // leading (left) column of the sprite
	ticks  int
	sprint int // remaining sprint ticks
}

func (d *dino) tick() tea.Cmd {
	return tea.Tick(time.Second/dinoFPS, func(time.Time) tea.Msg { return dinoTickMsg{} })
}

// boost makes the dino sprint briefly — fired when the user selects
// something, so navigation has a little kinetic feedback.
func (d *dino) boost() {
	d.sprint = dinoSprintLen
}

func (d *dino) paused() bool {
	return d.sprint == 0 && d.ticks%(dinoPauseEvery+dinoPauseLen) >= dinoPauseEvery
}

func (d *dino) advance(width int) {
	d.ticks++
	if d.paused() {
		return
	}
	stride := dinoStrideCols
	if d.sprint > 0 {
		d.sprint--
		stride = dinoSprintCols
	}
	d.x += stride
	spriteW := len([]rune(dinoSkyHigh))
	if width > 0 && d.x > width {
		// Ran off the right edge; re-enter from the left.
		d.x = -spriteW
	}
}

// clip trims a sprite row to the visible [0, width) range for a sprite whose
// left edge is at column start. It returns the visible runes and the column
// they begin at; ok is false when nothing is visible.
func clip(row []rune, start, width int) (vis []rune, at int, ok bool) {
	if start+len(row) <= 0 || start >= width {
		return nil, 0, false
	}
	if start < 0 {
		row = row[-start:]
		start = 0
	}
	if start+len(row) > width {
		row = row[:width-start]
	}
	return row, start, true
}

// renderGround draws the dino's three rows: two sky lines holding head and
// body, and a full-width braille seafloor with the legs spliced in (their
// blank edge cells clear the ground so the sprite stands out).
func (d *dino) renderGround(width int, t theme.Theme) string {
	if width < 1 {
		return ""
	}
	ground := make([]rune, width)
	for i := range ground {
		ground[i] = groundPattern[i%len(groundPattern)]
	}
	groundStyle := lipgloss.NewStyle().Foreground(t.Surface)
	dinoStyle := lipgloss.NewStyle().Foreground(t.Success).Bold(true)

	legs := dinoLegFrames[d.ticks%len(dinoLegFrames)]
	if d.paused() {
		legs = dinoLegsPause
	}
	pad := ""
	if d.sprint > 0 {
		pad = dinoDust
	}
	blankPad := strings.Repeat("⠀", len([]rune(pad)))

	sky := func(row string) string {
		line := []rune(strings.Repeat("⠀", width))
		vis, at, ok := clip([]rune(blankPad+row), d.x, width)
		if !ok {
			return groundStyle.Render(string(line))
		}
		return groundStyle.Render(string(line[:at])) +
			dinoStyle.Render(string(vis)) +
			groundStyle.Render(string(line[at+len(vis):]))
	}

	floor := groundStyle.Render(string(ground))
	if vis, at, ok := clip([]rune(pad+legs), d.x, width); ok {
		floor = groundStyle.Render(string(ground[:at])) +
			dinoStyle.Render(string(vis)) +
			groundStyle.Render(string(ground[at+len(vis):]))
	}
	return sky(dinoSkyHigh) + "\n" + sky(dinoSkyLow) + "\n" + floor
}
